/**
 * WorkflowEngine.ts — Pluggable background workflow runner.
 *
 * Hooks into the existing WatcherService's countdown callback (Stage 1 of the
 * two-stage detection system). When a file finishes writing, the engine checks
 * whether any registered workflows apply and runs them in the background —
 * completely independent of the organize pipeline.
 *
 * Design constraints:
 *   - PURELY ADDITIVE: zero modifications to WatcherService, ClassificationService,
 *     LearningService, or any other existing service
 *   - No new file watchers — uses the onFileReady() hook called from index.js
 *     inside the existing countdownCallback
 *   - One-at-a-time queue per workflow type (avoids hammering the LLM)
 *   - Retry once after 30 s on transient failures
 *   - Summary .txt files are NEVER re-processed (checked via sentinel + extension)
 *   - Settings-driven: each workflow can be toggled independently
 *   - No new npm packages
 */

import path from "path";
import { isSummaryFile, runPDFSummary, WorkflowResult } from "./workflows/PDFSummaryWorkflow";

// ── Types ──────────────────────────────────────────────────────────────────

/** Signature for a settings getter. Returns the stored value or a default. */
type SettingsGetter = (key: string, defaultValue: boolean) => boolean;

/** One item in the per-workflow processing queue. */
interface QueueItem {
  filePath:   string;
  retryCount: number;
}

// ── Constants ──────────────────────────────────────────────────────────────

/** Key used in appSettingsStore to persist the PDF-summary toggle. */
export const PREF_PDF_SUMMARY_ENABLED = "workflows.pdfSummaryEnabled";

/** How long to wait before retrying a failed workflow (ms). */
const RETRY_DELAY_MS = 30_000;

/** Max retries per file per workflow. */
const MAX_RETRIES = 1;

// ── Internal state ─────────────────────────────────────────────────────────

/** Queue for PDF summary jobs (one active at a time to protect LLM context). */
const pdfQueue: QueueItem[] = [];
let pdfQueueRunning = false;

/** Injected settings reader — provided by index.js at init time. */
let getSettings: SettingsGetter | null = null;

/** Optional renderer notification callback — set by index.js. */
type NotifyFn = (channel: string, payload: unknown) => void;
let notify: NotifyFn | null = null;

// ── Helpers ────────────────────────────────────────────────────────────────

/**
 * True if the file should be skipped entirely by the workflow engine.
 *
 * Skips:
 *   - Summary files generated by PDFSummaryWorkflow (sentinel-tagged .txt)
 *   - Any .txt file whose name ends in "-summary.txt" (belt-and-suspenders)
 *   - Hidden files (start with ".")
 */
function shouldSkipWorkflow(filePath: string): boolean {
  const base = path.basename(filePath);
  if (base.startsWith(".")) return true;

  // Belt-and-suspenders: skip any *-summary.txt regardless of sentinel
  if (base.endsWith("-summary.txt")) return true;

  // Deep check: read sentinel from the file header
  if (isSummaryFile(filePath)) return true;

  return false;
}

/** Read a boolean setting, falling back to `defaultVal` if not set. */
function getSetting(key: string, defaultVal: boolean): boolean {
  if (!getSettings) return defaultVal;
  return getSettings(key, defaultVal);
}

// ── PDF Queue ──────────────────────────────────────────────────────────────

/**
 * Drain the PDF summary queue one item at a time.
 * If a job fails, it is re-queued with retryCount+1 after RETRY_DELAY_MS.
 * Only runs while pdfSummaryEnabled is true.
 */
async function drainPdfQueue(): Promise<void> {
  if (pdfQueueRunning) return;
  pdfQueueRunning = true;

  while (pdfQueue.length > 0) {
    // Re-check toggle before each item (user may have disabled mid-queue)
    if (!getSetting(PREF_PDF_SUMMARY_ENABLED, false)) {
      console.log("[WorkflowEngine] PDF summary disabled — pausing queue.");
      break;
    }

    const item = pdfQueue.shift()!;
    console.log(`[WorkflowEngine] Running PDFSummary for: ${path.basename(item.filePath)}`);

    let result: WorkflowResult;
    try {
      result = await runPDFSummary(item.filePath);
    } catch (err: any) {
      result = { ok: false, reason: err?.message ?? String(err) };
    }

    if (result.ok) {
      console.log(`[WorkflowEngine] PDFSummary OK → ${result.outputPath}`);
      notify?.("workflow:pdf-summary-done", {
        sourcePath:  item.filePath,
        summaryPath: result.outputPath,
        filename:    path.basename(item.filePath),
      });
    } else {
      console.warn(`[WorkflowEngine] PDFSummary failed (${result.reason})`);

      if (item.retryCount < MAX_RETRIES) {
        console.log(`[WorkflowEngine] Will retry in ${RETRY_DELAY_MS / 1000}s…`);
        setTimeout(() => {
          pdfQueue.push({ filePath: item.filePath, retryCount: item.retryCount + 1 });
          // Restart drain if it stopped
          if (!pdfQueueRunning) drainPdfQueue();
        }, RETRY_DELAY_MS);
      } else {
        console.warn(`[WorkflowEngine] PDFSummary giving up after ${MAX_RETRIES} retries: ${path.basename(item.filePath)}`);
      }
    }
  }

  pdfQueueRunning = false;
}

// ── Public API ─────────────────────────────────────────────────────────────

/**
 * Initialize the engine.
 * Must be called once from index.js after app is ready.
 *
 * @param settingsGetter   Function that reads a boolean from appSettingsStore
 * @param notifyRenderer   Function that sends an IPC event to the renderer window
 */
export function initWorkflowEngine(
  settingsGetter: SettingsGetter,
  notifyRenderer?: NotifyFn
): void {
  getSettings = settingsGetter;
  notify      = notifyRenderer ?? null;
  console.log("[WorkflowEngine] Initialized.");
}

/**
 * Called from the existing countdownCallback in index.js whenever a file
 * finishes its Stage-1 write-detection debounce.
 *
 * This is the ONLY entry point — no new watchers needed.
 *
 * @param filename   Basename (e.g. "report.pdf")
 * @param filePath   Absolute path to the new file
 */
export function onFileReady(filename: string, filePath: string): void {
  if (!getSettings) return; // Not initialized yet

  // Global skip guard
  if (shouldSkipWorkflow(filePath)) {
    return;
  }

  const ext = path.extname(filename).toLowerCase();

  // ── PDF Summary workflow ───────────────────────────────────────────────
  if (ext === ".pdf" && getSetting(PREF_PDF_SUMMARY_ENABLED, false)) {
    pdfQueue.push({ filePath, retryCount: 0 });
    console.log(`[WorkflowEngine] Queued PDF summary for: ${filename}`);
    // Fire-and-forget — engine manages its own async queue
    drainPdfQueue().catch((err) => {
      console.warn("[WorkflowEngine] drainPdfQueue error:", err);
    });
  }

  // ── Future workflows can be added here ────────────────────────────────
  // if (ext === ".jpg" && getSetting(PREF_IMAGE_TAG_ENABLED, false)) { ... }
}

/**
 * How many jobs are currently pending in the PDF queue.
 * Useful for status display.
 */
export function getPdfQueueLength(): number {
  return pdfQueue.length;
}
