/**
 * PDFSummaryWorkflow.ts — Auto-summarize new PDFs using the on-device LLM.
 *
 * Triggered by WorkflowEngine when a new .pdf is detected in a watched folder.
 * Silently extracts up to 2000 words, sends them to Llama, and writes a
 * companion `[filename]-summary.txt` file in the same directory.
 *
 * Design constraints:
 *   - Zero new npm packages (uses existing TextExtractionService + LlamaService)
 *   - Summary .txt files are tagged with SUMMARY_SENTINEL so WorkflowEngine
 *     can identify and skip them (they must never trigger another workflow)
 *   - Never throws — returns { ok: false, reason } on any failure
 *   - Works entirely offline
 */

import fs   from "fs";
import path from "path";

import { extractText }                  from "../TextExtractionService";
import { generate, isReady, getError }  from "../LlamaService";

// ── Constants ──────────────────────────────────────────────────────────────

/**
 * First line written into every summary file.
 * WorkflowEngine reads this to detect previously-generated summaries and
 * ensures they are never re-processed.
 */
export const SUMMARY_SENTINEL = "# AI_ORGANIZER_SUMMARY_v1";

/** Max tokens for the summary generation (kept short for speed on CPU). */
const MAX_SUMMARY_TOKENS = 400;

/** Temperature — low for factual summarization. */
const SUMMARY_TEMPERATURE = 0.2;

/** Generation timeout — PDFs can be large, allow up to 60 s. */
const SUMMARY_TIMEOUT_MS = 60_000;

// ── Types ──────────────────────────────────────────────────────────────────

export interface WorkflowResult {
  ok:         boolean;
  outputPath?: string;
  reason?:    string;
}

// ── Helpers ────────────────────────────────────────────────────────────────

/**
 * Return the path where the summary file should be written.
 * e.g.  /Downloads/report.pdf  →  /Downloads/report-summary.txt
 */
export function getSummaryPath(pdfPath: string): string {
  const dir  = path.dirname(pdfPath);
  const base = path.basename(pdfPath, path.extname(pdfPath));
  return path.join(dir, `${base}-summary.txt`);
}

/**
 * True if `filePath` is a summary file generated by this workflow.
 * Reads only the first line — cheap and avoids loading the full file.
 */
export function isSummaryFile(filePath: string): boolean {
  try {
    const ext = path.extname(filePath).toLowerCase();
    if (ext !== ".txt") return false;

    // Read only enough bytes to check the sentinel
    const fd  = fs.openSync(filePath, "r");
    const buf = Buffer.alloc(SUMMARY_SENTINEL.length + 2);
    fs.readSync(fd, buf, 0, buf.length, 0);
    fs.closeSync(fd);
    return buf.toString("utf8").startsWith(SUMMARY_SENTINEL);
  } catch {
    return false;
  }
}

// ── Main workflow ──────────────────────────────────────────────────────────

/**
 * Run the PDF summary workflow for `pdfPath`.
 *
 * Steps:
 *   1. Validate: must be a .pdf, Llama must be ready
 *   2. Extract text (up to 2000 words) via TextExtractionService
 *   3. Build a concise summarisation prompt
 *   4. Generate summary with local Llama (single-shot, non-streaming)
 *   5. Write sentinel + summary to companion .txt file
 *
 * @returns WorkflowResult — always resolves, never rejects
 */
export async function runPDFSummary(pdfPath: string): Promise<WorkflowResult> {
  try {
    // ── Step 1: Validate ───────────────────────────────────────────────────
    const ext = path.extname(pdfPath).toLowerCase();
    if (ext !== ".pdf") {
      return { ok: false, reason: `Not a PDF: ${ext}` };
    }

    if (!isReady()) {
      const err = getError();
      return {
        ok:     false,
        reason: err ? `LLM not ready: ${err}` : "LLM not ready (still loading)",
      };
    }

    // ── Step 2: Extract text ───────────────────────────────────────────────
    const rawText = await extractText(pdfPath);
    if (!rawText || rawText.trim().length < 20) {
      return { ok: false, reason: "PDF yielded no extractable text (image-only or encrypted)" };
    }

    // Trim to 2000 words to keep the prompt within the 4096-token context
    const words    = rawText.trim().split(/\s+/);
    const excerpt  = words.slice(0, 2000).join(" ");
    const filename = path.basename(pdfPath);

    // ── Step 3: Build prompt ───────────────────────────────────────────────
    const prompt = [
      `You are a document summarizer. Summarize the following text from "${filename}" in 3-5 concise bullet points.`,
      "Focus on key information, decisions, and action items. Do not include any preamble.",
      "",
      "TEXT:",
      excerpt,
      "",
      "SUMMARY:",
    ].join("\n");

    // ── Step 4: Generate ───────────────────────────────────────────────────
    const summary = await generate(prompt, {
      maxTokens:   MAX_SUMMARY_TOKENS,
      temperature: SUMMARY_TEMPERATURE,
      timeoutMs:   SUMMARY_TIMEOUT_MS,
    });

    if (!summary || summary.trim().length === 0) {
      return { ok: false, reason: "LLM returned empty summary" };
    }

    // ── Step 5: Write output ───────────────────────────────────────────────
    const outputPath = getSummaryPath(pdfPath);
    const timestamp  = new Date().toISOString();
    const content = [
      SUMMARY_SENTINEL,
      `# Summary of: ${filename}`,
      `# Generated: ${timestamp}`,
      `# Source: ${pdfPath}`,
      "",
      summary.trim(),
      "",
    ].join("\n");

    fs.writeFileSync(outputPath, content, "utf-8");
    console.log(`[PDFSummaryWorkflow] Summary written → ${outputPath}`);

    return { ok: true, outputPath };

  } catch (err: any) {
    const reason = err?.message ?? String(err);
    console.warn(`[PDFSummaryWorkflow] Failed for ${pdfPath}: ${reason}`);
    return { ok: false, reason };
  }
}
